import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { BookingService } from '../../core/services/booking'; import { ShowsService, Show } from '../../core/services/shows'; import { MovieService, Movie } from '../../core/services/movie'; import { CinemasService, Cinema } from '../../core/services/cinemas';
@Component({selector:'app-booking',imports:[CommonModule,RouterLink],templateUrl:'./booking.html',styleUrl:'./booking.css'})
export class Booking implements OnInit{
 private route=inject(ActivatedRoute);private router=inject(Router);private bookingService=inject(BookingService);private showsService=inject(ShowsService);private movieService=inject(MovieService);private cinemasService=inject(CinemasService);show=signal<Show|null>(null);movie=signal<Movie|null>(null);cinema=signal<Cinema|null>(null);selectedSeats=signal<string[]>([]);loading=signal(true);booking=signal(false);errorMessage=signal('');successMessage=signal('');readonly rows='ABCDEFGHIJ'.split('');readonly seatNumbers=Array.from({length:20},(_,i)=>i+1);
 ngOnInit():void{if(!localStorage.getItem('token')){this.router.navigate(['/login']);return;}const id=Number(this.route.snapshot.queryParamMap.get('show_id'));if(!id){this.errorMessage.set('No show was selected. Please choose a show first.');this.loading.set(false);return;}this.loadShow(id)}
 private loadShow(id:number):void{this.showsService.getShowById(id).subscribe({next:s=>{this.show.set(s);this.loading.set(false);this.selectedSeats.set([]);this.movieService.getMovieById(s.movie_id).subscribe({next:m=>this.movie.set(m)});this.cinemasService.getCinemaById(s.cinema_id).subscribe({next:c=>this.cinema.set(c)})},error:()=>{this.loading.set(false);this.errorMessage.set('Unable to load the selected show.')}})}
 seatId(row:string,n:number):string{return`${row}${n}`}isBooked(seat:string):boolean{return this.show()?.booked_seats?.includes(seat)??false}isSelected(seat:string):boolean{return this.selectedSeats().includes(seat)}toggleSeat(seat:string):void{if(this.isBooked(seat)||this.booking())return;this.selectedSeats.update(c=>c.includes(seat)?c.filter(s=>s!==seat):[...c,seat]);this.errorMessage.set('')}get totalPrice():number{return this.selectedSeats().length*Number(this.show()?.ticket_price||0)}
 confirmBooking():void{const s=this.show();if(!s||this.booking())return;if(!this.selectedSeats().length){this.errorMessage.set('Please select at least one seat.');return}this.booking.set(true);this.errorMessage.set('');this.bookingService.createBooking({show_id:s.id,selected_seats:this.selectedSeats()}).subscribe({next:r=>{this.booking.set(false);this.router.navigate(['/payment',r.bookingId])},error:e=>{this.booking.set(false);if(e.status===401){localStorage.removeItem('token');localStorage.removeItem('user');this.router.navigate(['/login']);return}this.errorMessage.set(e.error?.message||'Booking failed. Please try again.');if(e.status===409)this.loadShow(s.id)}})}
}
