import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms';
import { MovieService, Movie } from '../../core/services/movie'; import { BookingService, Booking } from '../../core/services/booking'; import { ShowsService, Show } from '../../core/services/shows'; import { CinemasService, Cinema } from '../../core/services/cinemas';
@Component({selector:'app-admin',imports:[CommonModule,FormsModule],templateUrl:'./admin.html',styleUrl:'./admin.css'})
export class Admin implements OnInit{
 private moviesService=inject(MovieService);private bookingsService=inject(BookingService);private showsService=inject(ShowsService);private cinemasService=inject(CinemasService);movies=signal<Movie[]>([]);bookings=signal<Booking[]>([]);shows=signal<Show[]>([]);cinemas=signal<Cinema[]>([]);loading=signal(true);message=signal('');editingId=signal<number|null>(null);form:Partial<Movie>={title:'',description:'',genre:'',duration:120,release_date:'',rating:8,poster:''};
 ngOnInit():void{this.refresh()}refresh():void{this.loading.set(true);this.moviesService.getMovies().subscribe({next:m=>this.movies.set(m)});this.showsService.getShows().subscribe({next:s=>this.shows.set(s)});this.cinemasService.getCinemas().subscribe({next:c=>this.cinemas.set(c)});this.bookingsService.getAllBookings().subscribe({next:b=>{this.bookings.set(b);this.loading.set(false)},error:()=>this.loading.set(false)})}
 get revenue():number{return this.bookings().reduce((n,b)=>n+Number(b.total_price||0),0)}get tickets():number{return this.bookings().reduce((n,b)=>n+b.seats_booked,0)}
 editMovie(m:Movie):void{this.editingId.set(m.id);this.form={...m};window.scrollTo({top:0,behavior:'smooth'})}resetForm():void{this.editingId.set(null);this.form={title:'',description:'',genre:'',duration:120,release_date:'',rating:8,poster:''}}
 saveMovie():void{if(!this.form.title||!this.form.genre){this.message.set('Title and genre are required.');return}const request=this.editingId()?this.moviesService.updateMovie(this.editingId()!,this.form):this.moviesService.createMovie(this.form);request.subscribe({next:()=>{this.message.set(this.editingId()?'Movie updated successfully.':'Movie created successfully.');this.resetForm();this.refresh()},error:e=>this.message.set(e.error?.message||'Could not save movie.')})}
 deleteMovie(m:Movie):void{if(!confirm(`Delete ${m.title}?`))return;this.moviesService.deleteMovie(m.id).subscribe({next:()=>{this.message.set('Movie deleted successfully.');this.refresh()},error:e=>this.message.set(e.error?.message||'Delete failed.')})}
}
